In [6]:
import pandas as pd
import numpy as np
from itertools import product
from scipy.stats import norm
from scipy.optimize import minimize
import matplotlib.pyplot as plt

In [7]:
# fais un dataframe avec les données brutes
data_rating_raw = pd.read_csv("../data/credit_ratings/sectors_quater.csv")

In [ ]:
df = data_rating_raw.copy()

                year
count  179452.000000
mean     2015.993157
std         3.123474
min      2010.000000
25%      2013.000000
50%      2016.000000
75%      2018.000000
max      2023.000000

Importation et nettoyage des données

In [12]:
df.head()

,year_quarter,obligor_name,rating_agency_name,rating,rating_action_date,legal_entity_identifier,year_month,year,pays,nace,next_rating
0,2022-07-01,"06 ENVIRONMENTAL, LLC",Egan-Jones Ratings Company,B,2022-07-22,NaN,2022-07-01,2022.0,NaN,RU,B
1,2021-07-01,"11065220 Canada, Inc.",Fitch Ratings,B,2021-08-18,549300ETSKJL315VDV79,2021-08-01,2021.0,NaN,RU,D
2,2019-04-01,"18 Fremont Street Acquisition, LLC",Moody's Investors Service,B,2019-06-06,5493000QK0X0K188BR60,2019-06-01,2019.0,US,RU,C
3,2019-07-01,"18 Fremont Street Acquisition, LLC",Moody's Investors Service,B,2019-07-01,5493000QK0X0K188BR60,2019-07-01,2019.0,US,RU,C
4,2019-10-01,"18 Fremont Street Acquisition, LLC",Moody's Investors Service,B,2019-10-01,5493000QK0X0K188BR60,2019-10-01,2019.0,US,RU,C